---
editor: 
  markdown: 
    wrap: 72
---

# Resultados

## Resumo

Com o objetivo de tornar os resultados deste estudo acessíveis de forma
interativa e transparente, foi desenvolvido um **dashboard em R
utilizando o pacote Shiny**, disponível no seguinte endereço:

<https://beatrizmarques.shinyapps.io/cumprimento_metas/>

O painel permite a visualização detalhada do **cumprimento das metas de
redução de mortes no trânsito** estabelecidas pelo PNATRANS para os
municípios brasileiros classificados como não outliers (n = 4.473).

A interface é organizada por **unidades da federação**, e cada aba
apresenta:

-   **Gráfico de dispersão**: mostra a variação proporcional do número
    de mortes em 2023 em relação à média de 2018–2020, destacando os
    municípios que atingiram ou não suas metas;

-   **Gráfico de barras**: exibe o percentual de municípios que
    cumpriram as metas em cada estado e capital;

-   ️ **Tabela interativa**: apresenta, para cada município, informações
    como população, frota, número de mortes em 2023, meta
    individualizada e se foi atingida;

O dashboard foi desenvolvido para ser uma **ferramenta de visualização
do cumprimento das metas**, possibilitando a identificação de áreas
críticas e de boas práticas locais.

## Abas

O dashboard foi estruturado com um menu lateral que organiza o conteúdo
por **unidades da federação**, facilitando a navegação e a análise
regionalizada do cumprimento das metas.

Cada aba representa um estado brasileiro (ou o consolidado nacional
“Brasil”) e, ao ser selecionada, exibe um conjunto de visualizações e
informações específicas para os municípios daquela unidade federativa.
Essa estrutura permite ao usuário realizar consultas direcionadas,
comparações regionais e identificar padrões de desempenho na redução de
mortes no trânsito.

## Conteúdo

Para cada aba (UF), o conteúdo apresentado inclui:

-   Média de mortes no trânsito (2018-2020)

-   Número de mortes no trânsito (2023);

-   Percentual de municípios que já atingiram a meta;

-   Total de municípios contabilizados no cálculo (não outliers);

-   Qual era a meta estabelecida para o total;

-   Percentual de redução ou aumento no número de mortes;

-   Gráfico de barras por estado;

-   Gráfico de barras por capital;

-   Gráfico de dispersão: meta estabelecida x meta atingida;

-   Tabela interativa.

### Gráfico de Barras

Os gráficos de barras mostram o desempenho de cada estado e capital na
redução das mortes no trânsito. Por serem interativos, é possível passar
o cursor sobre as barras para visualizar o desempenho detalhado de cada
unidade da federação. As barras à esquerda de 0% indicam redução no
número de mortes, enquanto as à direita indicam aumento em 2023. Em cada
aba, as barras do estado e da respectiva capital ficam em destaque para
facilitar a visualização.

### Gráfico de Dispersão

O gráfico de dispersão representa o percentual de alcance da meta em
relação ao valor estabelecido. O eixo X exibe a meta de redução, sempre
expressa em valores negativos. O eixo Y indica o percentual já atingido
por cada município: valores negativos correspondem a um desempenho
abaixo do esperado (contrário à meta), enquanto valores positivos
indicam progresso. Cada ponto representa um município, com a cor
vermelha indicando aumento no número de mortes e a verde, redução. Ao
passar o cursor sobre os pontos, são exibidas informações detalhadas:
nome do município, estado, meta de redução, percentual de redução, média
de mortes (2018–2020) e número de mortes em 2023.

### Tabela

A Tabela apresenta a lista de todos os municípios que tinham uma meta
estabelecida. Nela, é possível verificar todas as informações de cada
município, incluindo o total da frota e o número de habitantes em 2023.
Os municípios estão ordenados por prioridade (1-27) e é possível
pesquisar um município específico através da barra de pesquisa no canto
direito superior da tabela. Para facilitar a análise, há também um
filtro que permite visualizar apenas os municípios que já atingiram a
meta ou os que não atingiram.
